### ISSUE TITLE
你这个规则有些问题，会干掉百度搜索结果右边的百度热搜。。。

### ISSUE THREAD

**Issue by RuningLittleSnail** [KPI0/uBlock-Origin_custom-rules#4]

**Comment by RuningLittleSnail** [comment]
baidu.com##.container_2AHLd.cr-content
baidu.com##.FYB_RD
baidu.com##div.c-font-normal

这几条，不知道哪一条

**Comment by KPI0** [comment]
> baidu.com##.container_2AHLd.cr-content baidu.com##.FYB_RD baidu.com##div.c-font-normal
> 
> 这几条，不知道哪一条

**Comment by KPI0** [comment]
> baidu.com##.container_2AHLd.cr-content baidu.com##.FYB_RD baidu.com##div.c-font-normal
> 
> 这几条，不知道哪一条

弄好了

**Comment by RuningLittleSnail** [comment]
谢谢！
