### ISSUE TITLE
www.toutiao.com首页误杀！

### ISSUE THREAD

**Issue by RuningLittleSnail** [KPI0/uBlock-Origin_custom-rules#5]
![toutiao](https://user-images.githubusercontent.com/128003407/227179049-fad0ed1e-5668-4164-ad31-bc2b588e02e3.JPG)
图片上这些条目

**Comment by KPI0** [comment]
> ![toutiao](https://user-images.githubusercontent.com/128003407/227179049-fad0ed1e-5668-4164-ad31-bc2b588e02e3.JPG) 图片上这些条目

toutiao.com##.left-container这条误杀已删除，更新订阅试试看

**Comment by RuningLittleSnail** [comment]
谢谢！
